const mongoose = require('mongoose');

const reminderSchema = new mongoose.Schema(
  {
    shopId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Shop',
      required: true,
    },
    customerId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Customer',
      required: true,
    },
    type: {
      type: String,
      enum: ['payment_due', 'follow_up', 'custom'],
      required: [true, 'Reminder type is required'],
    },
    title: {
      type: String,
      required: [true, 'Reminder title is required'],
      trim: true,
      maxlength: [200, 'Title cannot exceed 200 characters'],
    },
    message: {
      type: String,
      maxlength: [1000, 'Message cannot exceed 1000 characters'],
    },
    amount: {
      type: Number,
      default: null,
      min: [0, 'Amount cannot be negative'],
    },
    scheduledAt: {
      type: Date,
      required: [true, 'Scheduled date is required'],
    },
    reminderChannels: {
      type: [String],
      enum: ['push', 'sms', 'whatsapp', 'call'],
      default: ['push'],
    },
    status: {
      type: String,
      enum: ['pending', 'sent', 'acknowledged', 'snoozed', 'cancelled'],
      default: 'pending',
    },
    sentAt: {
      type: Date,
      default: null,
    },
    acknowledgedAt: {
      type: Date,
      default: null,
    },
    snoozeUntil: {
      type: Date,
      default: null,
    },
    snoozeCount: {
      type: Number,
      default: 0,
    },
    recurrence: {
      type: String,
      enum: ['none', 'daily', 'weekly', 'monthly'],
      default: 'none',
    },
    recurrenceEndDate: {
      type: Date,
      default: null,
    },
    parentReminderId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Reminder',
      default: null,
    },
    autoGenerated: {
      type: Boolean,
      default: false,
    },
    priority: {
      type: String,
      enum: ['low', 'medium', 'high'],
      default: 'medium',
    },
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    isDeleted: {
      type: Boolean,
      default: false,
    },
  },
  {
    timestamps: true,
  }
);

// Indexes
reminderSchema.index({ shopId: 1, scheduledAt: 1, status: 1 });
reminderSchema.index({ shopId: 1, customerId: 1, status: 1 });
reminderSchema.index({ status: 1, scheduledAt: 1 });
reminderSchema.index({ shopId: 1, isDeleted: 1 });

// Virtual for overdue status
reminderSchema.virtual('isOverdue').get(function () {
  return this.status === 'pending' && new Date() > this.scheduledAt;
});

reminderSchema.set('toJSON', { virtuals: true });
reminderSchema.set('toObject', { virtuals: true });

// Static method to get due reminders
reminderSchema.statics.getDueReminders = function (minutesAhead = 5) {
  const now = new Date();
  const futureTime = new Date(now.getTime() + minutesAhead * 60000);
  
  return this.find({
    status: 'pending',
    isDeleted: false,
    scheduledAt: { $lte: futureTime },
    $or: [
      { snoozeUntil: null },
      { snoozeUntil: { $lte: now } },
    ],
  })
    .populate('customerId', 'name phone currentBalance')
    .populate('shopId', 'name')
    .sort({ scheduledAt: 1 });
};

module.exports = mongoose.model('Reminder', reminderSchema);
